### ISSUE TITLE
[bug] DLL can't be loaded when Rocket League is running in bootcamp

### ISSUE THREAD

**Issue by fabianvf** [fabianvf/SpeedDrillPlugin#5]
but all other plugins seem to work.

**Comment by gabighali** [comment]
When attempting to load plugin via BakkesMod console: _plugin load speeddrill_ the error below is returned:
LoadLibrary returned NULL. Make sure the DLL is 64 bit and has access to all included libraries. Error code: 126

**Comment by fabianvf** [comment]
Fixed in 0.5

Please reopen if you see it again
